### ISSUE TITLE
libreria log.py

### ISSUE THREAD

**Issue by Paso94** [WEEE-Open/WOL#1]
Serve scrivere la libreria [log](https://github.com/WEEE-Open/WOL/blob/master/libs/log.py). Si può utilizzare parte di codice da [weeelab](https://github.com/WEEE-Open/weeelab/blob/master/weeelab), però userei ```|``` come separatore dei campi, la data in formato [Unix](https://it.wikipedia.org/wiki/Tempo_(Unix)) per semplificare lo sviluppo (ed evitare facili bug) e il telegramID come indentificativo in modo da poter essere usato insieme alla libreria [user.py](https://github.com/WEEE-Open/WOL/blob/master/libs/users.py)

**Comment by lvps** [comment]
I dati in formato human-readable di solito sono un vantaggio, la data UNIX è illeggibile... l'importante è usare una libreria decente, che prende come input la data nel formato in cui è adesso lo converte in un oggetto su cui si possono effettuare operazioni (somma, differenza, etc... con altre date o intervalli di tempo). Pure la libreria standard di PHP funziona così, sono sicuro che ci sia qualcosa di equivalente in Python.

Il telegramID di nuovo rende i dati non human-readable, e per alcuni non è noto, mentre il nome e cognome di tutti è ben noto. Alla fine `nome.cognome` è solo un altro identificatore arbitrario, basta che da qualche parte sia associato a nome e cognome effettivi, invece di calcolarli da lì come mi pare che faccia welab adesso, che se qualcuno ha spazi nel cognome non va bene.

Finché i tutti i campi tranne l'ultimo hanno una struttura fissa non c'è bisogno di inventarsi altri separatori: adesso il bot esplode (o esplodeva, se è stato fixato) se trova delle parentesi quadre nelle attività svolte, ma è l'ultimo campo, è l'unico che è composto da testo libero, gli altri sono date o username (caratteri alfabetici ASCII minuscoli e punto) che hanno una struttura standard e sono ben delimitati: basta leggere tutti quelli e poi dire «Da qui a fine riga c'è il campo "attività svolte"», qualunque cosa contenga.  
Altrimenti appena metto un `|` nelle attività siamo daccapo. Certo, inizia a esserci qualche problema se nel testo ci sono degli a capo, ma la libreria lo accetta come stringa: basta rimuoverli o sostituirli con spazio o lanciare un'eccezione o qualsiasi altra cosa.

Il discorso cambia se vogliamo usare SQLite invece di un file di testo buttato lì, ma la mole di dati non è così ingestibile e il file si può aprire con qualsiasi editor di testo per rapide ispezioni o modifiche al volo, il database un po' meno...

**Comment by Paso94** [comment]
Al momento ho rinominato **log.py** in **works.py** per riservare il nome **log** ai log di sistema e fatto in modo che salvasse secondo il formato `%Y-%m-%d_%H:%M:%S`, mantenendo però lo standard Unix per le classi.
Per ora tengo `|` come separatore e metterò dei controlli per evitare `\n` nei testi. SQLite direi di lasciarlo perdere.
Per il classico `nome.cognome` (aboliamo gli spazi o usiamo `_` ) ci lavorerò.
